### ISSUE TITLE
Github Actions setup option

### ISSUE THREAD

**Issue by maximousblk** [Revadike/epicgames-freebies-claimer#27]
Instead of running this on your own computer, you can use [GitHub actions](https://github.com/features/actions) to run it every day automatically. This will help if you don't always have access to your personal computer e.g. if you live in a hostel, where you can't just write your password in a file and assume nobody will see it.

You can create a repository with an action which runs this project. But you can't store plaintext credentials in a public repository. (you can do this with a private repository but you need to write a separate action to first edit the config.js). You can use secrets in github actions which nobody but only you can access.

Using github actions would also mean that you don't have to update it manually. It would clone the latest version and everything will be automatic.

**Comment by maximousblk** [comment]
I was just too exited to see this project that I didn't properly read the README. Sorry

**Comment by maximousblk** [comment]
I tried this by duplicating this repo to a private repo and it works flawlessly

here is a screen shot (I already have GTA V):

![image](https://user-images.githubusercontent.com/28438021/82084974-e4f54300-9709-11ea-8497-15d318919c21.png)


#29 can be a problem but I tried it 6 times and it worked everytime.

If I leave the 2FA_SECRET blank, it fails, but if i set to `1234`, it works. 

Here is the workflow file if you want to try it out:

```yaml
name: Claim

on:
  schedule:
    - cron:  '0 0 * * *' # Everyday
  push:
    
jobs:
  claim:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Install Dependencies
      run: npm install
    - name: Get them sweet freebies
      run: npm run start
```

**Comment by maximousblk** [comment]
I tried to do this without me cloning the whole repo and uploading it to a private repo by creating only one workflow file. It kept failing for some reason. Turns out, it was a problem with my password. If the password contains `&`, It bugs out out the commandline. I changed the password to something that doesn't have `&` in it and it worked.

here is a screen shot (I already have GTA V):

![image](https://user-images.githubusercontent.com/28438021/82116827-f8e08980-9789-11ea-8651-0664d8198cf5.png)

Here is the workflow file if you want to try it out:

```yaml
name: Claim games

on:
  schedule:
    - cron: '0 0 * * *' # Everyday
  push:
    
jobs:
  claim:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'Revadike/epicgames-freebies-claimer'
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: install dependencies
      run: npm install
    - name: claim
      run: npm run start ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} 0
```

Ceate corresponding secrets and let it run.

If this works for everyone, that would be awesome. You won't need the `loop` option anymore.
