### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by maximousblk** [Revadike/epicgames-freebies-claimer#43]
Am I doing something wrong?

![image](https://user-images.githubusercontent.com/28438021/87810156-27f2a480-c87a-11ea-85bf-e2ccd9bafb18.png)

workflow file:

```yml
name: Claim Epic Freebies
on:
  push:
    paths:
      - '.github/workflows/epic.yml'
  watch:
    types: [started]
  schedule: 
    - cron: "0 10 * * *"

jobs:
    claim:
        runs-on: ubuntu-latest

        timeout-minutes: 5

        steps:
            - name: Setup repo
              uses: actions/checkout@v2
              with:
                  repository: "Revadike/epicgames-freebies-claimer"

            - name: Setup Node.js
              uses: actions/setup-node@v1

            - name: Install dependencies
              run: yarn

            - name: Get Epic Freebies
              id: epic
              run: yarn start ${{ secrets.EPICUSERNAME }} ${{ secrets.EPICPASSWORD }} 0
```
